//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Comm_DL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Comm_DL() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Comm_DL", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 请按提示操作 的本地化字符串。
        /// </summary>
        internal static string 借或贷错误 {
            get {
                return ResourceManager.GetString("借或贷错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有错！必须按照分录金额填写 的本地化字符串。
        /// </summary>
        internal static string 借方发生科目数值错误 {
            get {
                return ResourceManager.GetString("借方发生科目数值错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请按规范的摘要填写 的本地化字符串。
        /// </summary>
        internal static string 发生项摘要错误 {
            get {
                return ResourceManager.GetString("发生项摘要错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生额错！发生额只能填写在一个方向上 的本地化字符串。
        /// </summary>
        internal static string 发生额双方向填写 {
            get {
                return ResourceManager.GetString("发生额双方向填写", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向错！请根据会计分录上本科目标出的方向选择填写位置 的本地化字符串。
        /// </summary>
        internal static string 发生额方向错误 {
            get {
                return ResourceManager.GetString("发生额方向错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期应与业务日期相同 的本地化字符串。
        /// </summary>
        internal static string 日期错误 {
            get {
                return ResourceManager.GetString("日期错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余额计算有错！余额=上日余额+同方向发生额-反方向发生额 的本地化字符串。
        /// </summary>
        internal static string 最终余额错误 {
            get {
                return ResourceManager.GetString("最终余额错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有错！必须按照分录金额填写 的本地化字符串。
        /// </summary>
        internal static string 贷方发生科目数值错误 {
            get {
                return ResourceManager.GetString("贷方发生科目数值错误", resourceCulture);
            }
        }
    }
}
