//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedLedger
    {
        public int Row_ID { get; set; }
        public decimal BalanceSum { get; set; }
        public string BalanceAbstract { get; set; }
        public string SubjectName { get; set; }
        public decimal DebitSum { get; set; }
        public decimal CreditSum { get; set; }
        public string Abstract { get; set; }
        public System.DateTime TimeMark { get; set; }
        public decimal FinalSum { get; set; }
        public int TchRoutineID { get; set; }
        public int TchNodeID { get; set; }
        public string RoutineDesc { get; set; }
        public string BankName { get; set; }
        public short BalanceOrient { get; set; }
    }
}
