//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int Row_ID { get; set; }
        public System.DateTime TimeMark { get; set; }
        public string ClientName { get; set; }
        public string BankName { get; set; }
        public string VoucherNo { get; set; }
        public decimal EntryAmount { get; set; }
        public string ClientAcc { get; set; }
        public int TchRoutineID { get; set; }
        public string TchRoutineTag { get; set; }
        public string Purpose { get; set; }
        public string MoneySource { get; set; }
    }
}
