//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentActivity
    {
        public int Row_ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime TimeMark { get; set; }
        public int TchRoutineID { get; set; }
        public int TchNodeID { get; set; }
        public int IsFinished { get; set; }
    }
}
