//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectItem
    {
        public int Row_ID { get; set; }
        public string SubjectName { get; set; }
        public string SubjectType { get; set; }
        public string ChangeOrient { get; set; }
        public string SubjectOrient { get; set; }
        public string SubSubject { get; set; }
        public decimal Amount { get; set; }
        public string NextLedger { get; set; }
        public int TchRoutineID { get; set; }
        public int TchNodeID { get; set; }
    }
}
